config/routes.rb
Rails.application.routes.draw do
  get 'home/home'

  root 'home#home'

  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  get '/short_urls/new'
  post '/short_urls/create'

  get '/short_urls' => 'short_urls#index'

  get '/:id' => 'short_urls#original_url'

  delete 'short_urls' => 'short_urls#destroy'

  post '/short_visits/create'

  get 'short_visits/show' => 'short_visits#show'

end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
  belongs_to :user
  has_many :short_visits

  validates_presence_of :original_url

  after_create :generate_short_url

  def generate_short_url
    self.shorty = self.id.to_s(36)
    self.save
  end
end

app/models/short_visit.rb
class ShortVisit < ActiveRecord::Base
  has_many :short_visits
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :short_urls, dependent: :destroy
  has_secure_password
  validates_presence_of :name, :email
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def remote_ip
    if request.remote_ip == '::1'
      '106.51.15.26'
    else
      request.remote_ip
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController

  before_filter :authorize
  require 'open-uri'


  def new
    @short_url=ShortUrl.new
  end

  def create
    @short_url = ShortUrl.new(user_params)
    if @short_url.save
      redirect_to short_urls_path
    else
      render :new
    end
  end

  def index
    @short_urls=current_user.short_urls.paginate(:page => params[:page], :per_page => 10)
  end

  def original_url
    url = ShortUrl.find_by_shorty(shorty_params[:id])
    location=find_location
    if url.present?
      url.short_visits.create(visitor_ip:location["ip"],visitor_city:location["country"],visitor_country_iso2:location["loc"])
      url.visits_count+=1
      url.save
      redirect_to url.original_url
    end
  end

  def destroy
    ShortUrl.find_by_id(params[:short_url_id]).destroy
    redirect_to short_urls_path
  end

  def find_location
    response = open("http://ipinfo.io/#{remote_ip}").read
    JSON.parse(response)
  end

  private

  def user_params
    params.require(:short_url).permit(:original_url, :user_id,:id)
  end

  def shorty_params
    params.permit(:id)
  end

end

app/controllers/short_visits_controller.rb
class ShortVisitsController < ApplicationController

  before_filter :authorize

  def show
    @short_visit=ShortVisit.where(short_url_id:params[:short_url_id]).last(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :api_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/helpers/short_visits_helper.rb
module ShortVisitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/home.html.erb
<div class="container">

  <div class="jumbotron">
    <h1>URL Shortener</h1>
    <p>A URL shortener is a Web site which converts long urls to short urls.</p>
    <p>
      <%=link_to "Url Shortener",short_urls_path,class:"btn btn-lg btn-primary"%>
    </p>
  </div>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to 'ShortUrl', short_urls_path %></li>
            <li><%= link_to "#{current_user.name}",'#'%></li>
            <li><%= link_to "Logout", '/logout' %></li>
        <% else %>
            <li><%= link_to 'Login', '/login' %></li>
            <li><%= link_to 'Signup', '/signup' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectUrlShortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header"%></br></br>

<%= yield %>

</body>
</html>

app/views/short_urls/index.html.erb
<div class="container">
  <h1>Listing Short Urls</h1>
  <div id="notice" class="alert alert-success"></div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Original Url</th>
      <th>Shorty Url</th>
      <th>Visits Count</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <%@short_urls.each do |short_url|%>
        <tr>
          <td><%=short_url.original_url%></td>
          <td><%=link_to "http://localhost:3000/"+short_url.shorty,"/#{short_url.shorty}"%></td>
          <td><%=short_url.visits_count%></td>
          <td><%= link_to "Delete",short_urls_path(short_url_id: short_url), :method => :delete, class:'btn btn-danger' %>
            <%= link_to "Recent Location",short_visits_show_path(short_url_id:short_url.id), class:'btn btn-primary' %>
          </td>
        </tr>
    <%end%>
    </tbody>
  </table>
  <%= will_paginate @short_urls %>
  <%= button_to "Generate Short Url", short_urls_new_path, method: :get, class: "btn btn-primary" %>
</div>

app/views/short_urls/new.html.erb
<% provide(:title, "New Shorty") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Short Url</h1>
    <%= form_for(:short_url, url: '/short_urls/create') do |f| %>

        <%= f.label :original_url %>
        <%= f.text_field :original_url, class: 'form-control' %>
        <%= f.label :short_url %>
        <%= f.text_field :shorty, class: 'form-control',disabled: true %>

        <%= f.hidden_field :user_id, value: current_user.id %></br>

        <%= f.submit "Generate shortUrl", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/short_visits/show.html.erb
<div class="container">
  <h1>Last 10 Short Visits</h1>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Visitor IP</th>
      <th>Visitor Country</th>
      <th>Location</th>
    </tr>
    </thead>
    <tbody>
    <%@short_visit.each do |short_vist|%>
        <tr>
          <td><%=short_vist.visitor_ip%></td>
          <td><%=short_vist.visitor_city%>
          <td><%=short_vist.visitor_country_iso2%></td>
        </tr>
    <%end%>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :api_token %><br>
      <%= f.text_field :api_token %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Api token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Signup!</h1>
    <%= form_for(:user, url: '/users' ) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %></br>

        <%= f.submit "Sign in", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Api token:</strong>
  <%= @user.api_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>